import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";

dayjs.extend(relativeTime);

function Avatar(props: { src: string; className?: string }) {
  return (
    <Image
      src={props.src}
      width={56}
      height={56}
      className={props.className + "h-14 w-14 rounded-full"}
      alt="Profile Image"
    />
  );
}

function CreatePost() {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex items-center gap-3 ">
      <Avatar src={user.profileImageUrl} />
      <input
        type="text"
        placeholder="type some emojis"
        className="grow bg-transparent p-5 outline-none"
      />
    </div>
  );
}

//we need one element from the getall function in post
type PostWithUser = RouterOutputs["posts"]["getAll"][number];

function PostsView(props: PostWithUser) {
  const { post, author } = props;

  return (
    <div key={post.id} className="flex gap-3  border-b border-slate-400 p-4 ">
      <Avatar src={author.profilePicture} />

      <div className="flex flex-col">
        <div className="flex text-slate-300">
          <span>{`@${author.username}`}</span>{" "}
          <span className="ml-2">{dayjs(post.createdAt).fromNow()}</span>
        </div>

        <span>{post.content}</span>
      </div>
    </div>
  );
}

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();
  const user = useUser();

  if (isLoading) return <div>loading..</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center ">
        <div className="h-full w-full border-x border-slate-400  md:max-w-2xl">
          <div className="flex items-center  border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {!!user.isSignedIn && <CreatePost />}
          </div>
          <div className="flex flex-col">
            {data?.map((fullPost) => (
              <PostsView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
